name: Countries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  Country:
    name: ${{ matrix.country }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Original source
        include:
          - country: Albania
            west: 19.3
            south: 39.62
            east: 21.02
            north: 42.69
          - country: Armenia
            west: 43.58
            south: 38.74
            east: 46.51
            north: 41.25
          - country: Austria
            west: 9.48
            south: 46.43
            east: 16.98
            north: 49.04
          - country: Belgium
            west: 2.51
            south: 49.53
            east: 6.16
            north: 51.48
          - country: Bulgaria
            west: 22.38
            south: 41.23
            east: 28.56
            north: 44.23
          - country: Bosnia and Herzegovina
            west: 15.75
            south: 42.65
            east: 19.6
            north: 45.23
          - country: Belarus
            west: 23.2
            south: 51.32
            east: 32.69
            north: 56.17
          - country: Switzerland
            west: 6.02
            south: 45.78
            east: 10.44
            north: 47.83
          - country: Cyprus
            west: 32.26
            south: 34.57
            east: 34
            north: 35.17
          - country: Czech Republic
            west: 12.24
            south: 48.56
            east: 18.85
            north: 51.12
          - country: Germany
            west: 5.99
            south: 47.3
            east: 15.02
            north: 54.98
          - country: Denmark
            west: 8.09
            south: 54.8
            east: 12.69
            north: 57.73
          - country: Algeria
            west: -8.68
            south: 19.06
            east: 12
            north: 37.12
          - country: Spain
            west: -9.39
            south: 35.95
            east: 3.04
            north: 43.75
          - country: Estonia
            west: 23.34
            south: 57.47
            east: 28.13
            north: 59.61
          - country: Finland
            west: 20.65
            south: 59.85
            east: 31.52
            north: 70.16
          - country: France
            west: -5
            south: 42.5
            east: 9.56
            north: 51.15
          - country: United Kingdom
            west: -7.57
            south: 49.96
            east: 1.68
            north: 58.64
          - country: Greece
            west: 20.15
            south: 34.92
            east: 26.6
            north: 41.83
          - country: Croatia
            west: 13.66
            south: 42.48
            east: 19.39
            north: 46.5
          - country: Hungary
            west: 16.2
            south: 45.76
            east: 22.71
            north: 48.62
          - country: Ireland
            west: -9.98
            south: 51.67
            east: -6.03
            north: 55.13
          - country: Italy
            west: 6.75
            south: 36.62
            east: 18.48
            north: 47.12
          - country: Lithuania
            west: 21.06
            south: 53.91
            east: 26.59
            north: 56.37
          - country: Luxembourg
            west: 5.67
            south: 49.44
            east: 6.24
            north: 50.13
          - country: Latvia
            west: 21.06
            south: 55.62
            east: 28.18
            north: 57.97
          - country: Moldova
            west: 26.62
            south: 45.49
            east: 30.02
            north: 48.47
          - country: Macedonia
            west: 20.46
            south: 40.84
            east: 22.95
            north: 42.32
          - country: Montenegro
            west: 18.45
            south: 41.88
            east: 20.34
            north: 43.52
          - country: Netherlands
            west: 3.31
            south: 50.8
            east: 7.09
            north: 53.51
          - country: Norway
            west: 4.99
            south: 58.08
            east: 31.29
            north: 70.92
          - country: Poland
            west: 14.07
            south: 49.03
            east: 24.03
            north: 54.85
          - country: Portugal
            west: -9.53
            south: 36.84
            east: -6.39
            north: 42.28
          - country: Romania
            west: 20.22
            south: 43.69
            east: 29.63
            north: 48.22
          - country: Russia
            west: -180
            south: 41.15
            east: 180
            north: 81.25
          - country: Serbia
            west: 18.83
            south: 42.25
            east: 22.99
            north: 46.17
          - country: Slovakia
            west: 16.88
            south: 47.76
            east: 22.56
            north: 49.57
          - country: Slovenia
            west: 13.7
            south: 45.45
            east: 16.56
            north: 46.85
          - country: Sweden
            west: 11.03
            south: 55.36
            east: 23.9
            north: 69.11
          - country: Turkey
            west: 26.04
            south: 35.82
            east: 44.79
            north: 42.14
          - country: Ukraine
            west: 22.09
            south: 44.36
            east: 40.08
            north: 52.34
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: bbox='{"north":${{ matrix.north }},"west":${{ matrix.west }},"south":${{ matrix.south }},"east":${{ matrix.east }}}' name="${{ matrix.country }}" npm run build
    - name: Display structure of downloaded files
      run: ls -R
    - name: Display structure of ouput files
      run: ls -R output/
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        path: ./output/
        name: ${{ matrix.country }}
